# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
